# Drupal with PostgreSQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: postgres
# Database username: postgres
# Database password: example
# ADVANCED OPTIONS; Database host: postgres

version: '3.3'

services:
  opigno:
    container_name: opigno
    hostname: opigno
    build: .
    ports:
      - 10000:80
    restart: always
    # volumes:
    #   - $PWD/sites:/var/www/html/sites
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.opigno.entrypoints=web
      - 'traefik.http.routers.opigno.rule=Host(`opigno.kdock.cloud`)'
      - traefik.http.services.opigno.loadbalancer.server.port=10000

  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: opigno
    volumes:
      - $PWD/mariadb-data:/var/lib/mysql
    restart: always
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.opigno.entrypoints=web
networks:
  web:
    external: true