version: '3.3'

services:
  opigno:
    container_name: opigno
    hostname: opigno
    build: .
    ports:
      - 10000:80
    restart: always
    environment:
      DRUPAL_TRUSTED_HOST: 'www\.example\.com'
#    command: [/bin/bash, -c, chmod 644 /var/www/html/web/sites/default/settings.php]
    networks:
      - web

  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: opigno
    command: [--max-allowed-packet=67108864]
    volumes:
      - ./mariadb-data:/var/lib/mysql
    restart: always
    networks:
      - web

networks:
  web:
